### ISSUE TITLE
Not working with new kernel

### ISSUE THREAD

**Issue by M1ch13l** [01org/thunderbolt-software-kernel-tree#1]
```
% dkms autoinstall
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -C ./ KVER=4.10.6-1-ARCH...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.10.6-1-ARCH (x86_64)
Consult /var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build/make.log for more information.
```
```
% cat /var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build/make.log
DKMS make.log for thunderbolt-icm-dkms-r2.2d1bd45 for kernel 4.10.6-1-ARCH (x86_64)
Tue Mar 28 13:14:54 CEST 2017
make: Entering directory '/var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build'
make -C /lib/modules/4.10.6-1-ARCH/build M=`pwd` modules
make[1]: Entering directory '/usr/lib/modules/4.10.6-1-ARCH/build'
  CC [M]  /var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build/icm_nhi.o
/var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build/icm_nhi.c:78:9: error: ‘GENL_ID_GENERATE’ undeclared here (not in a function)
  .id  = GENL_ID_GENERATE,
         ^~~~~~~~~~~~~~~~
/var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build/icm_nhi.c: In function ‘icm_nhi_init’:
/var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build/icm_nhi.c:1495:7: error: implicit declaration of function ‘genl_register_family_with_ops’ [-Werror=implicit-function-declaration]
  rc = genl_register_family_with_ops(&nhi_genl_family, nhi_ops);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:295: /var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build/icm_nhi.o] Error 1
make[1]: *** [Makefile:1490: _module_/var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.10.6-1-ARCH/build'
make: *** [Makefile:6: all] Error 2
make: Leaving directory '/var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build'
```

**Comment by levy-amir** [comment]
Options:
1. take old kernel version.
2. create patches from the top of the commits in the networking branch and apply them on your kernel.

**Comment by superm1** [comment]
@levy-amir are you guys force pushing changes over the old ones?  @Queuecumber and I were looking at fixing a DKMS package to work on more kernel versions and seeing some inconsistent results where commits have just randomly disappeared and new ones in their place.

**Comment by levy-amir** [comment]
Yes, we are force pushing changes.

**Comment by Queuecumber** [comment]
@levy-amir Do you guys need any help getting the code into a shape where it can be merged upstream?

**Comment by levy-amir** [comment]
Thank you very much for willing to help, but as you can see in https://lkml.org/lkml/2016/12/19/199, Mika@intel already on it.

**Comment by superm1** [comment]
@levy-amir At least for now until you guys are done with the rearchitecture could you rebase this tree on the latest 4.11-rc?  There are a few things that break on 4.11.  I've been trying to make the DKMS package as compatible as possible and did this for now:
https://github.com/dell/thunderbolt-icm-dkms/commit/c2ec86c848c773775daa35c5119b9dee8a62c81b

**Comment by michael-jamet** [comment]
@superm1 thanks for reporting, we're going to look into this

**Comment by levy-amir** [comment]
Tree is rebased with 4.11-rc5.

**Comment by levy-amir** [comment]
Fix macro redefinition with 4.11
